spring.application.name=microservicegateway

server.port=8888

# Eureka config
eureka.client.service-url.defaultZone=http://localhost:9999/eureka

# Route microservicepet
spring.cloud.gateway.server.webflux.routes[0].id=microservicepet
spring.cloud.gateway.server.webflux.routes[0].uri=lb://microservicepet
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/pet/**

# Route microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].id=microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].uri=lb://microserviceadopter
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/adopter/**

# Route microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].id=microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].uri=lb://microserviceadoptionrequest
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/adoption/**